repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - LICENSE
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - LICENSE
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-isoxpressor_logo_light.png
    - docs/images/nf-core-isoxpressor_logo_light.png
    - docs/images/nf-core-isoxpressor_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - LICENSE
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-isoxpressor_logo_light.png
    - docs/images/nf-core-isoxpressor_logo_light.png
    - docs/images/nf-core-isoxpressor_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  readme:
    - nextflow_badge

template:
  org: georgiakes
  name: isoxpressor
  description: This is the nextflow version of the tools IsoXpressor.
  author: Georgia Kesisoglou
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - ci
    - github_badges
    - gitpod
    - codespaces
    - license
    - adaptivecard
    - slackreport
    - vscode
  is_nfcore: false
